### ISSUE TITLE
setAllTouched after validateFail

### ISSUE THREAD

**Issue by jiangweiliu-aa** [tannerlinsley/react-form#171]
In react-form v1, once submit with validate fail, form will set all field touched, it is a reasonable implementation.
However, in react-form v2, set all field touched have been removed after `validate fail`.

Now what I did is running `setAllTouched` in `onValidationFail`. But I think this is a bad solution.
Since set all touched after submit with failure is an obvious user experience.

What should I do is better?

**Comment by joepuzzo** [comment]
Whenever you click on the submit button every field will get touched.. as long as your button is within the <form> and its type=submit

**Comment by jiangweiliu-aa** [comment]
I will try it, thank you!

**Comment by jiangweiliu-aa** [comment]
I checked my code, the button is within the form and its type is submit. 

I guess the problem is getTouched happens after `onValidationFail `. Am I right?

**Comment by joepuzzo** [comment]
Hmm that might be true... i will need to check that next chance i get

**Comment by jiangweiliu-aa** [comment]
@joepuzzo Run `onSubmitFailure` after dispatch submit, Does this work?

**Comment by SBoudrias** [comment]
Any update on this bug?

**Comment by joepuzzo** [comment]
So sumitting a form ( in general not in react form ) will cause all fields to blur. I leverage this because if you click on a submit button it will trigger all the fields on blurs which will then set the touched. It seems that this occurs after the validation failure happens. Im open to ideas but i dont know how to get around this atm
