### ISSUE TITLE
File objects replaced with empty plain objects on setValue call

### ISSUE THREAD

**Issue by dikond** [tannerlinsley/react-form#207]
Hi!

I've encountered an odd issue after update from v1.2.8 to v2.9.0. We have a custom FileInput component in our project which we are using for file attachments. Whenever the input is updated we are calling `fieldApi.setValue` with an instance of [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object.
```
setValue(e.target.files[0])
```
where argument was like
```
File
  lastModified: 1513010541000,
  lastModifiedDate: Date 2017-12-11T16:42:21.000Z,
  name: "image.png",
  size: 147342,
  type: "image/png",
  webkitRelativePath: "",
  __proto__: FilePrototype 
    constructor: function (),
    lastModified: Getter,
    lastModifiedDate: Getter,
    name: Getter,
    webkitRelativePath: Getter,
    __proto__: BlobPrototype { slice: slice(), size: Getter, type: Getter, … }
```
But for some reason we get `{}` object in form `values`. It is easy to check in `formDidUpdate` callback. I can confirm that in v1.2.8 it works.

I've tried to make a test to demonstrate this issue, but we don't have a File outside of browser 😞
I'm thinking about switching to base64 encoding of the file, but this will also require some back-end changes. Maybe you can recommend some alternatives?

**Comment by joepuzzo** [comment]
Hmm i have not needed to do this yet but its def somthing others have done.. to my knowledge, other people have base64 encoded the file. That being said... it should be working. All i am doing is taking whatever you pass to value and adding it to an object that will get submitted. Maybe try making a simple codesandbox with your custom input so i can see the issue.

**Comment by joepuzzo** [comment]
@dikond Status on this?

**Comment by dikond** [comment]
@joepuzzo Hello! I've tried to implement it on https://codesandbox.io, but it seems sandbox doesn't support File API and replaces files with its own stubs. Here is a link to this sandbox: https://codesandbox.io/s/43k62q2kw9
You can check the event target in console log once you attach a file via button.

I think codepen may support File better, but my experience with it was kinda frustrating.

**Comment by efournival** [comment]
Hi!
I'm getting the same problem. Basically I'm doing this to set the value of the field:
```HTML
<input type='file' onChange={(e) => setValue(e.target.files[0]) } />
```
At this point, if I replace `setValue` by `console.log` I get an object of type `File`, which is as expected.
However, when my form get submitted, instead of getting a `File`, I get an object.
When I give this to `FormData.append` it does not recognize a `File` to be uploaded and my server receive `[object Object]`, which is definitely not what I wanted.
I think there is a problem with `setValue`, maybe are you cloning the given parameter or something like that?
I need this to upload huge files, so base64-encoding is not an option for me.

**Comment by oas89** [comment]
This happens because there is some kind of "purification" in reducers, state containing form values is converted to JSON and vice versa (see https://github.com/react-tools/react-form/blob/master/src/redux/ReducerBuilder.js#L62).
`let newValues = JSON.parse(JSON.stringify(state.values));`
As a result form values could be only JSON serializable objects. Is it necessary procedure, could we allow form state contains arbitrary JS objects?

**Comment by joepuzzo** [comment]
I will look into this for V3

**Comment by davejm** [comment]
Is there are workaround for this that doesn't involve base64?

**Comment by davejm** [comment]
I see two places that do the JSON thing: https://github.com/react-tools/react-form/blob/c2337923284425e10620add45647e332be9c0459/src/components/Form.js#L28 and https://github.com/react-tools/react-form/blob/c2337923284425e10620add45647e332be9c0459/src/utils/index.js#L61. Although it only seems to be the former causing the immediate problem.. not sure

**Comment by carlos-vitallink360** [comment]
Why was this closed? this is still an issue.
