### ISSUE TITLE
[useForm] Warning: Function components cannot be given refs.

### ISSUE THREAD

**Issue by KubaJastrz** [tannerlinsley/react-form#369]
I see

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

when I run

```tsx
const ref = React.useRef()
const {Form} = useForm()

return <Form ref={ref} />
```

I think this is connected to https://github.com/tannerlinsley/react-form/blob/37c21cd02e03cfe8713ae6f93a4da3cfbb442459/src/hooks/useFormElement.js#L14

**Comment by Sidnioulz** [comment]
This has also been an issue for me, which has caused me to have to inject additional DOM elements in my form so I could have a `ref` and target the children of the form.

For the record, I need to map my form children in order to identify `<input>`s of fields with errors, and to identify the `submit` button.
