### ISSUE TITLE
Multiple validation on field

### ISSUE THREAD

**Issue by neomusic** [tannerlinsley/react-form#75]
I tried to apply multiple validation on field like this

```
        <Form
            onSubmit={(values) => {
              this.onSubmit(values)
            }}
            validate={(password}) => {
              return {
                password: !password ? 'Il campo è obbligatorio' : (password.length < 8 ? 'la password deve contenere almeno 8 caratteri' : undefined),
              }
            }}
          >{({ submitForm, getValue }) => {
            return (
             ...
            )
          }}
        </Form>
```

But it does not work. Can anyone help me? Thank you

**Comment by chungnho** [comment]
@neomusic In your example you're missing the starting brace around `{(password})`. Otherwise it looks correct. What isn't working?

The validate function will just be whatever you return in the Object. So figure out what `!password ? 'Il campo è obbligatorio' : (password.length < 8 ? 'la password deve contenere almeno 8 caratteri' : undefined)` evaluates to (and what `password` is being given to the function)

You can also simplify it down to make it more readable/easy to debug, eg
```
<Form
  onSubmit={values => this.onSubmit(values)}
  validate={{password} => {
    let passwordError
    if (!password) {
      passwordError = "Required"
    } else if (password.length < 8) {
      passwordError = "Too short"
    }
    console.log("Validating - password:", password, passwordError) // To debug
    return {
      password: passwordError
    }
  }}
>
. . .
</Form>
```
